import type { TreeNode } from '../dto/types';

export const getInitialElements = (): TreeNode[] => [
  {
    id: 'root',
    parentId: null,
    value: 'Root Element',
    isDeleted: false,
    children: [],
  },
  {
    id: 'A1',
    parentId: 'root',
    value: 'A1',
    isDeleted: false,
    children: [],
  },
  {
    id: 'A2_1',
    parentId: 'A1',
    value: 'A2_1',
    isDeleted: false,
    children: [],
  },
  {
    id: 'A3',
    parentId: 'A2_1',
    value: 'A3',
    isDeleted: false,
    children: [],
  },
  {
    id: 'A4',
    parentId: 'A3',
    value: 'A4',
    isDeleted: false,
    children: [],
  },
  {
    id: 'A5',
    parentId: 'A4',
    value: 'A5',
    isDeleted: false,
    children: [],
  },
  {
    id: 'A6',
    parentId: 'A5',
    value: 'A6',
    isDeleted: false,
    children: [],
  },
  {
    id: 'A2_2',
    parentId: 'A1',
    value: 'A2_2',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B1',
    parentId: 'root',
    value: 'B1',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B2_1',
    parentId: 'B1',
    value: 'B2_1',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B3',
    parentId: 'B2_1',
    value: 'B3',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B4',
    parentId: 'B3',
    value: 'B4',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B5',
    parentId: 'B4',
    value: 'B5',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B2_2',
    parentId: 'B1',
    value: 'B2_2',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B2_3',
    parentId: 'B1',
    value: 'B2_3',
    isDeleted: false,
    children: [],
  },
  {
    id: 'B3_1',
    parentId: 'B2_3',
    value: 'B3_1',
    isDeleted: false,
    children: [],
  },
];
