export const ERROR_CODES = {
  // Validation errors
  EMPTY_VALUE: 'EMPTY_VALUE',
  INVALID_PARENT_ID: 'INVALID_PARENT_ID',
  MISSING_ELEMENT_ID: 'MISSING_ELEMENT_ID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Not found errors
  ELEMENT_NOT_FOUND: 'ELEMENT_NOT_FOUND',
  PARENT_NOT_IN_CACHE: 'PARENT_NOT_IN_CACHE',

  // State errors
  ELEMENT_DELETED: 'ELEMENT_DELETED',
  ELEMENT_ALREADY_DELETED: 'ELEMENT_ALREADY_DELETED',

  // Operation errors
  UPDATE_FAILED: 'UPDATE_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
  CREATE_FAILED: 'CREATE_FAILED',

  // Generic errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',
  FASTIFY_ERROR: 'FASTIFY_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
